# Generated by Django 3.0.5 on 2021-06-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210618_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='year',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
