# Generated by Django 3.0.5 on 2021-06-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_titles_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
