# Generated by Django 3.0.5 on 2021-06-19 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210619_1240'),
        ('api', '0002_auto_20210619_1543'),
    ]

    operations = [
    ]
