# Generated by Django 3.0.5 on 2021-06-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210619_1408'),
        ('api', '0020_auto_20210622_1352'),
    ]

    operations = [
    ]
